name: Bale Viral Twitter Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

# اضافه کردن این بخش برای اطمینان از دسترسی نوشتن
permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # برای اینکه کل تاریخچه رو داشته باشه و در push خطا نده

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run bot
        env:
          BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python twitter_bot.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add sent.json || echo "No changes to add"
          git commit -m "Update sent tweets database" || echo "No changes to commit"
          git push origin main
