name: Twitter Bot

on:
  schedule:
    - cron: "*/20 * * * *"  # هر ۲۰ دقیقه
  workflow_dispatch:      # قابلیت اجرای دستی (برای تست)

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run Python Script
        env:
          BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python twitter_bot.py

      - name: Update Database
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sent.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "update database" && git push)
