name: Bale Viral Twitter Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run bot
        env:
          BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python twitter_bot.py
